
GET http://localhost:8000/api/books?limit=2

###

GET http://localhost:8000/api/auth
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJqYW5lLmRvZUBleGFtcGxlLmNvbSIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDA4NjA0M30.wLe1m72iS_Ww7rz1AHUSN0a6GmwN-9sQHU949Jj5JzQ
###

POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "jane.doe@example.com",
    "password": "SecurePassword123"
}
###

GET http://localhost:8000/api/vehicle-specifications/1


###

POST http://localhost:8000/api/register
Content-Type: application/json

{
    "fullName": "Jane Doe",
    "email": "jane.doe@example.com",
    "contactPhone": "1234567890",
    "address": "123 Main St, Anytown, USA",
    "role": "admin",
    "password": "SecurePassword123"
}

###

PUT http://localhost:8000/api/books/1
Content-Type: application/json

{
    "author": "KAVATHA"
}
###
DELETE http://localhost:8000/api/users/1

###

GET http://localhost:8000/api/books




