
GET http://localhost:8000/api/books?limit=2

###

GET https://hono-bookstore-api.onrender.com/api/books

###
GET https://hono-bookstore-api.onrender.com/api/books
###

GET http://localhost:8000/api/vehicle-specifications/1


###

POST http://localhost:8000/api/register
Content-Type: application/json

{
    "fullName": "John Doe",
    "email": "john.doe@example.com",
    "contactPhone": "1234567890",
    "address": "123 Main St, Anytown, USA",
    "role": "user",
    "password": "SecurePassword123"
}

###

PUT http://localhost:8000/api/books/1
Content-Type: application/json

{
    "author": "KAVATHA"
}
###
DELETE http://localhost:8000/api/users/1

###

GET http://localhost:8000/api/books




